# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: quay.io/dolfinadjoint/pyadjoint:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements_de.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install h5py --no-binary=h5py
            python3 -m pip install -r requirements_dev.txt
      - run:
          name: install package
          command: |
            python3 -m pip install .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}

      - restore_cache:
          keys:
          - v2-dolfin-jit-cache

      # run linting
      - run:
          name: run linting
          command: |
            make lint

      # run linting
      - run:
          name: run mypy
          command: |
            make type

      # run tests!
      - run:
          name: run tests
          command: |
            make test

      - save_cache:
          key: v2-dolfin-jit-cache
          paths:
            - ~/.cache/instant
            - ~/.cache/dijitso