version: 2.1
jobs:
  build-and-test:
    docker:
      - image: quay.io/dolfinadjoint/pyadjoint:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install h5py --no-binary=h5py
            python3 -m pip install -r requirements_dev.txt
            python3 -m pip install --upgrade pytest
      - run:
          name: install package
          command: |
            python3 -m pip install .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}

      - restore_cache:
          keys:
            - v2-dolfin-jit-cache

      # run linting
      - run:
          name: run linting
          command: |
            make lint

      # run linting
      - run:
          name: run mypy
          command: |
            make type

      # run tests!
      - run:
          name: run tests
          command: |
            make test

      - save_cache:
          key: v2-dolfin-jit-cache
          paths:
            - ~/.cache/instant
            - ~/.cache/dijitso

      - store_artifacts:
          path: htmlcov
          destination: htmlcov

      - run:
          name: codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build-and-test
