name: CI

on: [push]

jobs:
  build:
    name: Run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: pulse_adjoint
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install -r requirements_dev.txt
          python3 -m pip install git+https://github.com/dolfin-adjoint/pyadjoint.git
          python3 -m pip install .
      - name: Lint with flake8
        run: |
          make lint
      - name: Type checking with mypy
        run: |
          make type
      - name: Test with pytest
        run: |
          make test
